/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var Cave:String = "event:/Music/Cave";
    public static inline var OutsideTheMines:String = "event:/Music/OutsideTheMines";
}

class FmodSFX {
    public static inline var RatDamage:String = "event:/SFX/Enemy/Rat/RatDamage";
    public static inline var RatDeath:String = "event:/SFX/Enemy/Rat/RatDeath";
    public static inline var Crumble:String = "event:/SFX/Environment/Crumble";
    public static inline var Type:String = "event:/SFX/Hud/Type";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var CollectCoin:String = "event:/SFX/Player/Collect/CollectCoin";
    public static inline var FootstepRock:String = "event:/SFX/Player/Footsteps/FootstepRock";
    public static inline var ShovelEnemyImpact:String = "event:/SFX/Player/Shovel/ShovelEnemyImpact";
    public static inline var ShovelSwing:String = "event:/SFX/Player/Shovel/ShovelSwing";
    public static inline var PlayerTakeDamage:String = "event:/SFX/Player/TakeDamage/PlayerTakeDamage";
}
