/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var Cave:String = "event:/Music/Cave";
    public static inline var CrystalArea:String = "event:/Music/CrystalArea";
    public static inline var OutsideTheMines:String = "event:/Music/OutsideTheMines";
}

class FmodSFX {
    public static inline var CrystalBreak:String = "event:/SFX/Crystal/CrystalBreak";
    public static inline var CrystalHitPickaxe:String = "event:/SFX/Crystal/CrystalHitPickaxe";
    public static inline var CrystalHitShovel:String = "event:/SFX/Crystal/CrystalHitShovel";
    public static inline var CrystalNear:String = "event:/SFX/Crystal/CrystalNear";
    public static inline var BatDeath:String = "event:/SFX/Enemy/Bat/BatDeath";
    public static inline var BlobDeath:String = "event:/SFX/Enemy/Blob/BlobDeath";
    public static inline var BlobMove:String = "event:/SFX/Enemy/Blob/BlobMove";
    public static inline var RatDamage:String = "event:/SFX/Enemy/Rat/RatDamage";
    public static inline var RatDeath:String = "event:/SFX/Enemy/Rat/RatDeath";
    public static inline var SnakeDeath:String = "event:/SFX/Enemy/Snake/SnakeDeath";
    public static inline var SnakeVenom:String = "event:/SFX/Enemy/Snake/SnakeVenom";
    public static inline var Crumble:String = "event:/SFX/Environment/Crumble";
    public static inline var Type:String = "event:/SFX/Hud/Type";
    public static inline var Typewriter:String = "event:/SFX/Hud/Typewriter";
    public static inline var TypewriterFast:String = "event:/SFX/Hud/TypewriterFast";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var CollectCoin:String = "event:/SFX/Player/Collect/CollectCoin";
    public static inline var PlayerDeath:String = "event:/SFX/Player/Death/PlayerDeath";
    public static inline var PlayerFall:String = "event:/SFX/Player/Fall/PlayerFall";
    public static inline var FootstepRock:String = "event:/SFX/Player/Footsteps/FootstepRock";
    public static inline var LightFlickering:String = "event:/SFX/Player/Light/LightFlickering";
    public static inline var LightGoingOut:String = "event:/SFX/Player/Light/LightGoingOut";
    public static inline var LightRecharge:String = "event:/SFX/Player/Light/LightRecharge";
    public static inline var LightRechargeNoClick:String = "event:/SFX/Player/Light/LightRechargeNoClick";
    public static inline var LightWarning25Percent:String = "event:/SFX/Player/Light/LightWarning25Percent";
    public static inline var LightWarning50Percent:String = "event:/SFX/Player/Light/LightWarning50Percent";
    public static inline var MatterConverterClick:String = "event:/SFX/Player/Light/MatterConverterClick";
    public static inline var MatterConverterBlend:String = "event:/SFX/Player/MatterConverter/MatterConverterBlend";
    public static inline var MatterConverterCharge1:String = "event:/SFX/Player/MatterConverter/MatterConverterCharge1";
    public static inline var MatterConverterCharge2:String = "event:/SFX/Player/MatterConverter/MatterConverterCharge2";
    public static inline var MatterConverterCharge3:String = "event:/SFX/Player/MatterConverter/MatterConverterCharge3";
    public static inline var MatterConverterGears:String = "event:/SFX/Player/MatterConverter/MatterConverterGears";
    public static inline var MatterConverterNewCharge1:String = "event:/SFX/Player/MatterConverter/MatterConverterNewCharge1";
    public static inline var MatterConverterNewCharge2:String = "event:/SFX/Player/MatterConverter/MatterConverterNewCharge2";
    public static inline var MatterConverterNewCharge3:String = "event:/SFX/Player/MatterConverter/MatterConverterNewCharge3";
    public static inline var MatterConverterNewCharge4:String = "event:/SFX/Player/MatterConverter/MatterConverterNewCharge4";
    public static inline var MatterConverterNewCharge5:String = "event:/SFX/Player/MatterConverter/MatterConverterNewCharge5";
    public static inline var MatterConverterNewCharge6:String = "event:/SFX/Player/MatterConverter/MatterConverterNewCharge6";
    public static inline var Pop:String = "event:/SFX/Player/MatterConverter/Pop";
    public static inline var PlayerPurchase:String = "event:/SFX/Player/Purchase/PlayerPurchase";
    public static inline var PlayerPurchaseFail:String = "event:/SFX/Player/Purchase/PlayerPurchaseFail";
    public static inline var ShovelEnemyImpact:String = "event:/SFX/Player/Shovel/ShovelEnemyImpact";
    public static inline var ShovelEnemyImpactHighBass:String = "event:/SFX/Player/Shovel/ShovelEnemyImpactHighBass";
    public static inline var ShovelEnemyImpactHigherBass:String = "event:/SFX/Player/Shovel/ShovelEnemyImpactHigherBass";
    public static inline var ShovelSwing:String = "event:/SFX/Player/Shovel/ShovelSwing";
    public static inline var PlayerAlmostDead:String = "event:/SFX/Player/TakeDamage/PlayerAlmostDead";
    public static inline var PlayerTakeDamage:String = "event:/SFX/Player/TakeDamage/PlayerTakeDamage";
}
