/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var Cave:String = "event:/Music/Cave";
    public static inline var OutsideTheMines:String = "event:/Music/OutsideTheMines";
}

class FmodSFX {
    public static inline var BatDeath:String = "event:/SFX/Enemy/Bat/BatDeath";
    public static inline var BlobDeath:String = "event:/SFX/Enemy/Blob/BlobDeath";
    public static inline var BlobMove:String = "event:/SFX/Enemy/Blob/BlobMove";
    public static inline var RatDamage:String = "event:/SFX/Enemy/Rat/RatDamage";
    public static inline var RatDeath:String = "event:/SFX/Enemy/Rat/RatDeath";
    public static inline var SnakeDeath:String = "event:/SFX/Enemy/Snake/SnakeDeath";
    public static inline var SnakeVenom:String = "event:/SFX/Enemy/Snake/SnakeVenom";
    public static inline var Crumble:String = "event:/SFX/Environment/Crumble";
    public static inline var Type:String = "event:/SFX/Hud/Type";
    public static inline var Typewriter:String = "event:/SFX/Hud/Typewriter";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var CollectCoin:String = "event:/SFX/Player/Collect/CollectCoin";
    public static inline var PlayerDeath:String = "event:/SFX/Player/Death/PlayerDeath";
    public static inline var PlayerFall:String = "event:/SFX/Player/Fall/PlayerFall";
    public static inline var FootstepRock:String = "event:/SFX/Player/Footsteps/FootstepRock";
    public static inline var LightRecharge:String = "event:/SFX/Player/Light/LightRecharge";
    public static inline var MatterConverterClick:String = "event:/SFX/Player/Light/MatterConverterClick";
    public static inline var MatterConverterBlend:String = "event:/SFX/Player/MatterConverter/MatterConverterBlend";
    public static inline var MatterConverterCharge1:String = "event:/SFX/Player/MatterConverter/MatterConverterCharge1";
    public static inline var MatterConverterCharge2:String = "event:/SFX/Player/MatterConverter/MatterConverterCharge2";
    public static inline var MatterConverterCharge3:String = "event:/SFX/Player/MatterConverter/MatterConverterCharge3";
    public static inline var MatterConverterGears:String = "event:/SFX/Player/MatterConverter/MatterConverterGears";
    public static inline var Pop:String = "event:/SFX/Player/MatterConverter/Pop";
    public static inline var PlayerPurchase:String = "event:/SFX/Player/Purchase/PlayerPurchase";
    public static inline var PlayerPurchaseFail:String = "event:/SFX/Player/Purchase/PlayerPurchaseFail";
    public static inline var ShovelEnemyImpact:String = "event:/SFX/Player/Shovel/ShovelEnemyImpact";
    public static inline var ShovelSwing:String = "event:/SFX/Player/Shovel/ShovelSwing";
    public static inline var PlayerTakeDamage:String = "event:/SFX/Player/TakeDamage/PlayerTakeDamage";
}
